language: python
python:
  - 2.6
  - 2.7
  - 3.3
install: "pip install Django==$DJANGO_VERSION --use-mirrors"
script: ./runtests.py
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5

matrix:
  exclude:
   - python: 3.3
     env: DJANGO_VERSION=1.4.5
